services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grademanagement
    ports:
      - "5432:5432"
    volumes:
      - ./seed:/docker-entrypoint-initdb.d
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  grades-service:
    build: ../server/grades-service
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      DB_DSN: "postgres://postgres:postgres@postgres:5432/grademanagement?sslmode=disable"
      REDIS_ADDR: "redis:6379"
